version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn hirehop_tools.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hirehop_tools
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
