version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: hirehop_db
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: hirehop_tools
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    user: appuser
    volumes:
      - .:/app:rw,z
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: