version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: hirehop_db
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: hirehop_tools
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - /opt/hirehop:/app/ext:rw
    ports:
      - "8000:8000"
    depends_on:
      - db
